# -*- coding: utf-8 -*-
"""modular_program

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kRF30LPTo9cI6lDqkuH4batNIbibJr0r
"""

#Lucas Vandenakker
#CS175
#modular_program

def main():

  grade1 = getGrade()
  grade2 = getGrade()
  grade3 = getGrade()

  percentage_grade = (grade1 + grade2 + grade3) / 3

  print(f"Your final grade percentage is: {percentage_grade:.2f} ")

  print(f"You finished with a {letter_grade(percentage_grade)}")


def getGrade():
  userGrade = int(input("Enter a grade between 0 and 100: "))

  return userGrade

def letter_grade(percentage_grade):

  if(percentage_grade < 60):
    return "F"
  elif (percentage_grade < 70):
    return "D"
  elif (percentage_grade < 80):
    return "C"
  elif (percentage_grade < 90):
    return "B"
  else:
    return "A"

main()